version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes: 
      - /Users/chadoran/mongo:/data/db
    stdin_open: true
    tty: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root